<?php

	// Implementation hook_menu() 	 
	function ukabbalah_topics_menu() {
		
		$items = array();
			
		$items['courses'] = array(               // Made this a PAGE
			'page callback'      => 'getTopicsHtmlStructure',
			'access callback' => TRUE,
			'type'             => MENU_CALLBACK,
		);
			
		return $items;
		
	}
	
	// Get the HTML base Structure for the topics page
	function getTopicsHtmlStructure() {

		drupal_add_css(drupal_get_path('module', 'ukabbalah_topics') .'/css/customCarousel.css');	
		drupal_add_js(drupal_get_path('module', 'ukabbalah_topics') .'/js/json_carousel.js');
		$resultHTML = "";
		$resultHTML.="<div id='teachingsControlSection'>";
		$resultHTML.="<div id='teachingsControlSectionInnerWrapper'>";
		$resultHTML.="<span id='teachingsSectionTitle'>".t('COURSES')."</span>";
		$resultHTML.="<span id ='list'><a href = 'javascript:void(0)'><img src = 'sites/all/modules/ukabbalah_topics/images/list.ico'></a></span>";
		$resultHTML.="<span id ='grid'><a href = 'javascript:void(0)'><img src = 'sites/all/modules/ukabbalah_topics/images/grid.ico'></a></span>";	
		$resultHTML.="</div>";
		$resultHTML.="</div>";
		$resultHTML.="<div id='teachingsSectionHeaderBar'>";
		$resultHTML.="<div id='teachingsBarInnerWrapper'>";
		$resultHTML.="<div id='authorDDWrapper'>";
		$resultHTML.="<span id='teachersDDtext'>".t('Teacher')."</span>";
		$resultHTML.="<span id='teachersDD'>".getTeachersDropDown()."</span>";
		$resultHTML.="</div>";
		$resultHTML.="<div id='topicDDWrapper'>";
		$resultHTML.="<span id='topicDDtext'>".t('Topic')."</span>";
		$resultHTML.="<span id='topicDD'>".getTopicDropDown()."</span>";
		$resultHTML.="</div>";
		$resultHTML.="</div>";
		$resultHTML.="</div>";
		$resultHTML.="<div id='beginnersCoursesOnCollection'></div>";
		$resultHTML.="<div id='teachingResultSection'></div>";
		return $resultHTML;	
	}
	
	// Returns the Primary Topics Dropdown HTML
	function getTopicDropDown() {
		$topics =  taxonomy_get_tree( 14 ); // vid = 14 for Primary Topics
		$resultHTML = "<select id='teachings_topicDD'>";
		$resultHTML .="<option value='all'>All</option>";
		foreach( $topics as $t ) {
			$resultHTML .="<option value='cat".$t->tid."'>".$t->name."</option>";
		}
		$resultHTML .= "</select>";
		return $resultHTML;
	}
		
	// Returns the Authors Dropdown HTML	
	function getTeachersDropDown() {
		
		$teachers =  taxonomy_get_tree( 7 ); // vid = 7 for Authors
		$resultHTML = "<select id='teachings_teachersDD'>";
		$resultHTML .="<option value='all'>All</option>";
		foreach( $teachers as $t ) {
			$resultHTML .="<option value='cat".$t->tid."'>".$t->name."</option>";
		}
		$resultHTML .= "</select>";
		return $resultHTML;
		
	}
	