<?php
		
	// Step 1: Block Info
	function kabbalah_show_kcom_testimonials_block_info() {
    
		$blocks['kabbalah-testimonials'] = array(		
			'info' => t('Kabbalah Testimonials'),
		);
		return $blocks;
	}
	
	// Step 2: Block View Implementation
	function kabbalah_show_kcom_testimonials_block_view($delta = '') {
	
		// The $delta parameter tells us which block is being requested.
		switch ($delta) 
		{
			case 'kabbalah-testimonials':
				// Create your block content here
				$block['subject'] = t('Kabbalah Testimonials Block for front page');
				$block['content'] = kabbalah_custom_testimonial_show();
				break;
		}

		return $block;
	}
	
	function kabbalah_custom_testimonial_show() {

		drupal_add_css(drupal_get_path('module', 'kabbalah_show_kcom_testimonials') .'/css/kabbalah_show_kcom_testimonials.css');	
		drupal_add_js(drupal_get_path('module', 'kabbalah_show_kcom_testimonials') .'/js/kabbalah_show_kcom_testimonials.js');	// adding the js file for the module	
	
		$ch = curl_init();
		curl_setopt($ch, CURLOPT_URL,"http://kabbalah.com/get_kcom_testimonials_json");
		// receive server response ...
		curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
		$server_output = curl_exec ($ch);
		curl_close ($ch);
		
		$testimonials = json_decode($server_output);
		
		$resultHTML = "";
		$resultHTML .= "<div id='kcomTestimonialsSlideshow'>";
		foreach( $testimonials as $t) 
		{
			$resultHTML .= "<div>".$t->teaser."</div>";	
		}
		$resultHTML .= "</div>";
		return $resultHTML;
	}
	
	