<?php

	function kabbalah_custom_collection_pages_menu() {
		
		$items = array();
			
		$items['courses'] = array(               // Made this a PAGE
			'page callback'      => 'getCoursesHtmlStructure',
			'access callback' => TRUE,
			'type'             => MENU_CALLBACK,
		);
		
		$items['teachers'] = array(               // Made this a PAGE
			'page callback'      => 'getTeachersHtmlStructure',
			'access callback' => TRUE,
			'type'             => MENU_CALLBACK,
		);
		
		$items['event-lectures'] = array(               // Made this a PAGE
			'page callback'      => 'getOnlineDemandTopicsHtmlStructure',
			'access callback' => TRUE,
			'type'             => MENU_CALLBACK,
		);
		
		$items['other-languages'] = array(               // Made this a PAGE
			'page callback'      => 'getOtherLanguagesHtmlStructure',
			'access callback' => TRUE,
			'type'             => MENU_CALLBACK,
		);
		
		$items['live-events'] = array(               // Made this a PAGE
			'page callback'      => 'getLiveEventsHtmlStructure',
			'access callback' => TRUE,
			'type'             => MENU_CALLBACK,
		);
		
		$items['recommended-lessons'] = array(               // Made this a PAGE
			'title' => 'Recommended Lessons For This Week',
			'page callback'      => 'getRecommendedLessonsHtmlStructure',
			'access callback' => TRUE,
			'type'             => MENU_CALLBACK,
		);
		
			
		return $items;
		
	}

	// Courses Page HTML
	function getCoursesHtmlStructure() {

		drupal_add_js(drupal_get_path('module', 'kabbalah_custom_collection_pages') .'/js/custom_courses_collection.js');
		$resultHTML = "";
		$resultHTML.="<div id='teachingsControlSection'>";
		$resultHTML.="<div id='teachingsControlSectionInnerWrapper'>";
		$resultHTML.="<span id='teachingsSectionTitle'>".t('COURSES')."</span>";
		$resultHTML.="<span class='displayOption'>show page as: </span>";
		$resultHTML.="<span id ='list'><a id ='viewByList' href = 'javascript:void(0)' alt = 'view by list'></a></span>";
		$resultHTML.="<span id ='grid'><a id ='viewByGrid' href = 'javascript:void(0)' alt = 'view by grid'></a></span>";	
		$resultHTML.="</div>";
		$resultHTML.="</div>";
		$resultHTML.= headerBarSectionHTML();
		$resultHTML.="<div id='beginnersCoursesOnCollection'></div>";
		$resultHTML.="<div id='teachingResultSection'></div>";
		return $resultHTML;	
	}
	
	//Teachers Page HTML
	function getTeachersHtmlStructure() {
	
		drupal_add_js(drupal_get_path('module', 'kabbalah_custom_collection_pages') .'/js/custom_teachers_collection.js');
		$resultHTML = "";
		$resultHTML.="<div id='teachingsControlSection'>";
		$resultHTML.="<div id='teachingsControlSectionInnerWrapper'>";
		$resultHTML.="<span id='teachingsSectionTitle'>".t('TEACHERS')."</span>";	
		$resultHTML.="</div>";
		$resultHTML.="</div>";
		$resultHTML.= headerBarSectionHTML();
		$resultHTML.="<div id='teachingResultSection'></div>";
		return $resultHTML;	
	}
	
	// Event Lectures Page HTML 
	function getOnlineDemandTopicsHtmlStructure() {

		drupal_add_js(drupal_get_path('module', 'kabbalah_custom_collection_pages') .'/js/custom_event_lectures_collection.js');
		$resultHTML = "";
		$resultHTML.="<div id='teachingsControlSection'>";
		$resultHTML.="<div id='teachingsControlSectionInnerWrapper'>";
		$resultHTML.="<span id='teachingsSectionTitle'>".t('EVENT LECTURES')."</span>";	
		$resultHTML.="</div>";
		$resultHTML.="</div>";
		$resultHTML.= headerBarSectionHTML();
		$resultHTML.="<div id='teachingResultSection'></div>";
		return $resultHTML;	
	}
	
	// Other Languages Page HTML
	function getOtherLanguagesHtmlStructure() {

		drupal_add_js(drupal_get_path('module', 'kabbalah_custom_collection_pages') .'/js/custom_other_languages_collection.js');
		$resultHTML = "";
		$resultHTML.="<div id='teachingsControlSection'>";
		$resultHTML.="<div id='teachingsControlSectionInnerWrapper'>";
		$resultHTML.="<span id='teachingsSectionTitle'>".t('OTHER LANGUAGES')."</span>";
		$resultHTML.="</div>";
		$resultHTML.="</div>";
		$resultHTML.= headerBarSectionHTML();
		$resultHTML.="<div id='teachingResultSection'></div>";
		return $resultHTML;	
	}
	
	// Live Events Page HTML
	function getLiveEventsHtmlStructure() {

		drupal_add_js(drupal_get_path('module', 'kabbalah_custom_collection_pages') .'/js/custom_live_events_collection.js');
		$resultHTML = "";
		$resultHTML.="<div id='teachingsControlSection'>";
		$resultHTML.="<div id='teachingsControlSectionInnerWrapper'>";
		$resultHTML.="<span id='teachingsSectionTitle'>".t('LIVE EVENTS')."</span>";
		$resultHTML.="</div>";
		$resultHTML.="</div>";
		$resultHTML.="<div id='teachingsSectionHeaderBar'>";
		$resultHTML.="<div id='teachingsBarInnerWrapper'>";
		$resultHTML.="<div id='authorDDWrapper'>";
		$resultHTML.="<span id='teachersDDtext'>".t('Locations')."</span>";
		$resultHTML.="<span id='teachersDD'>".getLocationssDropDown()."</span>";
		$resultHTML.="</div>";
		$resultHTML.="</div>";
		$resultHTML.="</div>";
		$resultHTML.="<div id='teachingResultSection'></div>";
		return $resultHTML;	
	}
	
	// REcommended Lessons Page HTML
	
	function getRecommendedLessonsHtmlStructure() {
		
		$url = "https://university.kabbalah.com/k_api/rest/v__1/recommended_lsns/0/1";
		$ch = curl_init();
		curl_setopt($ch, CURLOPT_URL,$url);
		// receive server response ...
		curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
		$server_output = curl_exec ($ch);
		curl_close ($ch);
		$lessons = array();
		$lessons = json_decode( $server_output );
		
		$final_portion = getFinalPortion();
		
		$resultHTML = "";
		$resultHTML.="<div class='termDesc'>According to Kabbalah, every week comes woven with its own energy and opportunities for transformation. When you connect with each week's energy and its lessons, you'll be empowered to make major shifts in your life. Learn more with the lessons recommended for the energy of this week. <a href='/lessons/".str_replace(" ", "-", $final_portion )."'>View All Lessons on this week's portion ".$final_portion."</a></div>"; 	
		$resultHTML.="<ul class='masonry ulStyle'>";
		
		
		foreach( $lessons as $lesson )
		{
			$resultHTML.="<li class='masonry-brick eachCont'>";
			$resultHTML.="<span class='lessonBlockWrapper'>";
			$resultHTML.="<a href=".$lesson->path.">";
			$resultHTML.="<span class='lessonBlockImage'>";
			$resultHTML.="<span class='lessonBlockImageHover'></span><img src='".$lesson->image."' alt='lesson_img'/></span>";
			$resultHTML.="<span class='lessonBlockTitle'>".$lesson->title."</span>";
			$resultHTML.="<span class='lessonBlockTeacherInfo'>";
			$resultHTML.="<span>Teacher:</span>";
			$resultHTML.="<span>".$lesson->author."</span>";
			$resultHTML.="</span>";
			$resultHTML.="<span class='lessonBlockDetail'>";
			$resultHTML.="<span class='".$lesson->membership."'></span>";
			$resultHTML.="<span class=".$lesson->media_type."></span>";
			$resultHTML.="<span class='lessonBlockInfo'>".$lesson->created." </span>";
			$resultHTML.="</span>";
			$resultHTML.="</a>";
			$resultHTML.="</span>";	
			$resultHTML.="</li>";
		}
		
		$resultHTML.="</ul>";
		
		return $resultHTML;
	}
	

	// Header Bar Section HTML
	function headerBarSectionHTML() {
	
		$resultHTML = "";
		$resultHTML.="<div id='teachingsSectionHeaderBar'>";
		$resultHTML.="<div id='teachingsBarInnerWrapper'>";
		$resultHTML.="<div id='authorDDWrapper'>";
		$resultHTML.="<span id='teachersDDtext'>".t('Teacher')."</span>";
		$resultHTML.="<span id='teachersDD'>".getTeachersDropDown()."</span>";
		$resultHTML.="</div>";
		$resultHTML.="<div id='topicDDWrapper'>";
		$resultHTML.="<span id='topicDDtext'>".t('Topic')."</span>";
		$resultHTML.="<span id='topicDD'>".getTopicDropDown()."</span>";
		$resultHTML.="</div>";
		$resultHTML.="</div>";
		$resultHTML.="</div>";
		return $resultHTML;
	}
	
	// Primary Topics Dropdown HTML
	function getTopicDropDown() {
		$topics =  taxonomy_get_tree( 14 ); // vid = 14 for Primary Topics
		$resultHTML = "<select id='teachings_topicDD'>";
		$resultHTML .="<option value='all'>All</option>";
		foreach( $topics as $t ) {
			$resultHTML .="<option value='cat".$t->tid."'>".$t->name."</option>";
		}
		$resultHTML .= "</select>";
		return $resultHTML;
	}
		
	// Teachers Dropdown HTML	
	function getTeachersDropDown() {
		
		$teachers =  taxonomy_get_tree( 7 ); // vid = 7 for Authors
		$resultHTML = "<select id='teachings_teachersDD'>";
		$resultHTML .="<option value='all'>All</option>";
		foreach( $teachers as $t ) {
			$resultHTML .="<option value='cat".$t->tid."'>".$t->name."</option>";
		}
		$resultHTML .= "</select>";
		return $resultHTML;
		
	}
	
	// Locations Dropdown HTML	
	function getLocationssDropDown() {
		
		$locations =  taxonomy_get_tree( 17 ); // vid = 17 for Locations
		$resultHTML = "<select id='teachings_teachersDD'>";
		$resultHTML .="<option value='all'>All</option>";
		foreach( $locations as $t ) {
			$resultHTML .="<option value='cat".$t->tid."'>".$t->name."</option>";
		}
		$resultHTML .= "</select>";
		return $resultHTML;
		
	}
	
	
	