<?php

	// Implementation hook_menu() 	 
	function ukabbalah_authors_menu() {
		
		$items = array();
			
		$items['teachers'] = array(               // Made this a PAGE
			'page callback'      => 'getTeachersHtmlStructure',
			'access callback' => TRUE,
			'type'             => MENU_CALLBACK,
		);
	
		return $items;		
	}
	
	// Get the HTML base Structure for the authors page
	function getTeachersHtmlStructure() {

		drupal_add_css(drupal_get_path('module', 'ukabbalah_authors') .'/css/ukabbalah_authors.css');	
		drupal_add_js(drupal_get_path('module', 'ukabbalah_authors') .'/js/ukabbalah_authors.js');
		$resultHTML = "";
		$resultHTML.="<div id='teachingsControlSection'>";
		$resultHTML.="<span id='teachingsSectionTitle'>".t('TEACHERS')."</span>";	
		$resultHTML.="</div>";
		$resultHTML.="<div id='teachingsSectionHeaderBar'>";
		$resultHTML.="<div id='authorDDWrapper'>";
		$resultHTML.="<span id='teachersDDtext'>".t('Teacher')."</span>";
		$resultHTML.="<span id='teachersDD'>".getTeachersDropDown1()."</span>";
		$resultHTML.="</div>";
		$resultHTML.="<div id='topicDDWrapper'>";
		$resultHTML.="<span id='topicDDtext'>".t('Topic')."</span>";
		$resultHTML.="<span id='topicDD'>".getTopicDropDown1()."</span>";
		$resultHTML.="</div>";
		$resultHTML.="</div>";
		$resultHTML.="<div id='teachingResultSection'></div>";
		return $resultHTML;	
	}
	
	// Returns the Primary Authors Dropdown HTML
	function getTopicDropDown1() {
		$topics =  taxonomy_get_tree( 14 ); // vid = 14 for Primary Topics
		$resultHTML = "<select id='teachings_topicDD'>";
		$resultHTML .="<option value='all'>All</option>";
		foreach( $topics as $t ) {
			$resultHTML .="<option value='cat".$t->tid."'>".$t->name."</option>";
		}
		$resultHTML .= "</select>";
		return $resultHTML;
	}
		
	// Returns the Authors Dropdown HTML	
	function getTeachersDropDown1() {
		
		$teachers =  taxonomy_get_tree( 7 ); // vid = 7 for Authors
		$resultHTML = "<select id='teachings_teachersDD'>";
		$resultHTML .="<option value='all'>All</option>";
		foreach( $teachers as $t ) {
			$resultHTML .="<option value='cat".$t->tid."'>".$t->name."</option>";
		}
		$resultHTML .= "</select>";
		return $resultHTML;
		
	}
	

	function getTermNames1()	{
	
		$topics =  taxonomy_get_tree( 7 ); 
		$vnames = array();
		foreach( $topics as $t ) {
			$vnames[$t->tid] = $t->name;
		}
		return $vnames;
	}