<?php

	// Implementation hook_menu() 	 
	function ukabbalah_courses_by_language_menu() {
		
		$items = array();
			
		$items['other-languages'] = array(               // Made this a PAGE
			'page callback'      => 'getOtherLanguagesHtmlStructure',
			'access callback' => TRUE,
			'type'             => MENU_CALLBACK,
		);
			
		return $items;
		
	}
	
	// Get the HTML base Structure for the topics page
	function getOtherLanguagesHtmlStructure() {

		drupal_add_css(drupal_get_path('module', 'ukabbalah_courses_by_language') .'/css/customCarousel.css');	
		drupal_add_js(drupal_get_path('module', 'ukabbalah_courses_by_language') .'/js/json_carousel.js');
		$resultHTML = "";
		$resultHTML.="<div id='teachingsControlSection'>";
		$resultHTML.="<div id='teachingsControlSectionInnerWrapper'>";
		$resultHTML.="<span id='teachingsSectionTitle'>".t('OTHER LANGUAGES')."</span>";
		//$resultHTML.="<span id ='list'><a href = 'javascript:void(0)'><img src = 'sites/all/modules/ukabbalah_courses_by_language/images/list.ico'></a></span>";
		//$resultHTML.="<span id ='grid'><a href = 'javascript:void(0)'><img src = 'sites/all/modules/ukabbalah_courses_by_language/images/grid.ico'></a></span>";	
		$resultHTML.="</div>";
		$resultHTML.="</div>";
		$resultHTML.="<div id='teachingsSectionHeaderBar'>";
		$resultHTML.="<div id='teachingsBarInnerWrapper'>";
		$resultHTML.="<div id='authorDDWrapper'>";
		$resultHTML.="<span id='teachersDDtext'>".t('Teacher')."</span>";
		$resultHTML.="<span id='teachersDD'>".getTeachersDropDown3()."</span>";
		$resultHTML.="</div>";
		$resultHTML.="<div id='topicDDWrapper'>";
		$resultHTML.="<span id='topicDDtext'>".t('Topic')."</span>";
		$resultHTML.="<span id='topicDD'>".getTopicDropDown3()."</span>";
		$resultHTML.="</div>";
		$resultHTML.="</div>";
		$resultHTML.="</div>";
		$resultHTML.="<div id='beginnersCoursesOnCollection'></div>";
		$resultHTML.="<div id='teachingResultSection'></div>";
		return $resultHTML;	
	}
	
	// Returns the Primary Topics Dropdown HTML
	function getTopicDropDown3() {
		$topics =  taxonomy_get_tree( 14 ); // vid = 14 for Primary Topics
		$resultHTML = "<select id='teachings_topicDD'>";
		$resultHTML .="<option value='all'>All</option>";
		foreach( $topics as $t ) {
			$resultHTML .="<option value='cat".$t->tid."'>".$t->name."</option>";
		}
		$resultHTML .= "</select>";
		return $resultHTML;
	}
		
	// Returns the Authors Dropdown HTML	
	function getTeachersDropDown3() {
		
		$teachers =  taxonomy_get_tree( 7 ); // vid = 7 for Authors
		$resultHTML = "<select id='teachings_teachersDD'>";
		$resultHTML .="<option value='all'>All</option>";
		foreach( $teachers as $t ) {
			$resultHTML .="<option value='cat".$t->tid."'>".$t->name."</option>";
		}
		$resultHTML .= "</select>";
		return $resultHTML;
		
	}
	
	// Get an associative array tid=>tname for Course Language
	function getTermNames3()	{
	
		$topics =  taxonomy_get_tree( 16 ); // vid = 16 for Course Language
		$vnames = array();
		foreach( $topics as $t ) {
			$vnames[$t->tid] = $t->name;
		}
		return $vnames;
	}