<?php
	function _is_imobile() {
	  foreach (array('iphone', 'ipod', 'ipad') as $needle) {
		if (stripos($_SERVER["HTTP_USER_AGENT"], $needle) !== false) return true;
	  }
	  return false;
	}
	function theme_jwplayer_video($args){
		$video=$args['video'];
		$width = isset($args['width'])?$args['width']:512;
		$height = isset($args['height'])?$args['height']:288;
		$autoplay = isset($args['autoplay'])?$args['autoplay']:NULL;
		$skin ='/'.drupal_get_path('module','jwplayer').'/includes/five.xml';
		$file = $args['file'];
		static $players;
		if(!is_array($players)){
			$jwplayerjs = array(
			  '#tag' => 'script',
			  '#attributes' => array(
				'src' => '/'.drupal_get_path('module','jwplayer').'/includes/jwplayer.js',
				'type' => 'text/javascript',
			  ),
			);
			$jwplayerkey = array(
			  '#tag' => 'markup',
			  '#markup' => '<script type="text/javascript">jwplayer.key="EMiSmgYruQJsCca0ZeZej55r95Tvni0Ldhb6XwUF+ag=";</script>'
			);
			//drupal_add_html_head($jwplayerjs,'jwplayer-js');
			//drupal_add_html_head($jwplayerkey,'jwplayer-key');
			//drupal_add_js(drupal_get_path('module','jwplayer').'/includes/jwplayer.js');
			//drupal_add_js('jwplayer.key="EMiSmgYruQJsCca0ZeZej55r95Tvni0Ldhb6XwUF+ag=";','inline');
			drupal_add_js('https  ://content.jwplatform.com/libraries/DRDW0dXD.js', 'external');
			$players=array();

		}
		$player_id='jwplayer'.(count($players)+1);
		$players[]=$player_id;
		if(!is_string($video)) $jwplayer['video']=$video;
		
		
		// Adding the audio download link
		
		$audio_download = '<div id="wrapperDownloadAudio">
							<div class="buttonDownloadAudio">
								<a href="http://twistassets.kabbalah.com/videos/'.$video->vid.'/formats/Small_640x360_300kbps_64kbps_h264/file.mp3" target="_blank"><span>Download audio	</span> <img src="/sites/all/themes/ukabbalah/images/audioDownloadBtn.jpg" alt="download audio"></a>
							</div>
						   </div>';
		
		
		
		  $ga_array = array();
		  $ga_array['idstring'] = 'title';
		  $ga_array['trackingobject'] = 'pageTracker';
		  $ga_array = json_encode( $ga_array);
		  $mode = array();
		  $mode[]=array('type'=>'html5');
		  $mode[]=array('type'=>'flash','src'=> '/'.drupal_get_path('module','jwplayer').'/includes/jwplayer.flash.swf');
		  $mode=json_encode($mode);
		  
		$jwplayer['player_id']=$player_id;
		$jwplayer['settings']=array(
			'height' => 528 ,//$height,
			'width' => 940, //$width,
			//'autostart' => $autoplay,
			'related'=>array('file'=>$file),
			'skin'=> $skin,
			'modes'=>$mode,
			'ga'=> $ga_array,
			);
			
		$jwplayer['suffix'][]= $audio_download;
		
		drupal_alter('jwplayer_settings',$jwplayer);
		
		if( _is_imobile() && $jwplayer['video']->dotsub_settings['autostart_subtitles'] == 0 )
		{	
			$video_url_for_html5 = $jwplayer['settings']['playlist'][0]['sources'][0]['file'];
			$video_image_for_html5 = $jwplayer['settings']['playlist'][0]['image'];
						
			$html = "<video src='".$video_url_for_html5."' controls preload='auto' poster='".$video_image_for_html5."' height='435' width='800'>
						Your browser does not support the <code>video</code> element.
					</video>";
			$html .= $audio_download;		
		}
		else 
		{
			$html='<div id="playerbase"><span id="'.$player_id.'">No video</span></div>
				<script type="text/javascript">
					jwplayer("'.$player_id.'").setup('.json_encode($jwplayer['settings']).');
				</script>';
				
			if(isset($jwplayer['prefix'])) $html=implode('',$jwplayer['prefix']).$html;
			if(isset($jwplayer['suffix'])) $html.=implode('',$jwplayer['suffix']);		
		}
		
		
		// $html='<div id="playerbase"><span id="'.$player_id.'">No video</span></div>
			// <script type="text/javascript">
				// jwplayer("'.$player_id.'").setup('.json_encode($jwplayer['settings']).');
			// </script>';
		// if(isset($jwplayer['prefix'])) $html=implode('',$jwplayer['prefix']).$html;
		// if(isset($jwplayer['suffix'])) $html.=implode('',$jwplayer['suffix']);
		return $html;
	}
	function jwplayer_theme($existing, $type, $theme, $path) {
		return array(
			'jwplayer_video' => array(
				'arguments' => array('videos' => NULL, 'width' => 150, 'height' => NULL,'file'=>NULL, 'autoplay' => NULL),
			),
		);
	}