<?php
    
	function kabbalah_content_access_rule() 
	{
		
		// Getting the logged in user role 
		
		switch (getuser_role()) {
			case 'free':
				return 0;
				break;
			case 'basic':
			    return 1;
				break;
			case 'premium':
				return 2;
				break;
			case 'premium_plus':
				return 3;
				break;
			default:
			    return 10;
			
		}
		
	}
	
	function getuser_role(){
		global $user;
		$user_role = "";
		if (array_key_exists('5', $user->roles) ) {	return $user_role = $user->roles['5'];	}
		else 
		if (array_key_exists('6', $user->roles) ) {	return $user_role = $user->roles['6'];	}
		else 
		if (array_key_exists('8', $user->roles) ) {	return $user_role = $user->roles['8']; }
		else
		if (array_key_exists('9', $user->roles) ) {	return $user_role = $user->roles['9']; }
	}