<?php
		
	// D7 - Menu Hook 
	function kabbalah_custom_slideshow_menu() {
		
		$items['getSlideshowDataJson'] = array(               // Made this a PAGE
			'page callback' => 'getSlideshowDataJson',
			'access callback' => TRUE,
			'type' => MENU_NORMAL_ITEM,
		);

		return $items;
	  }
	  
	function getSlideshowDataJson() {
	
		$sql = 	"SELECT n.nid,n.title,n.changed,il.field_event_image_cdn_link_value,b.body_value,plv.field_event_path_link_value,st.field_sub_title_value,cs.field_color_selector_value,dso.field_display_order_value ".
				"FROM node n ".
				"LEFT JOIN {node_revision nr} ON ( n.nid = nr.nid ) ".
				"LEFT JOIN {field_revision_field_event_image_cdn_link il} ON ( nr.nid = il.entity_id AND nr.vid = il.revision_id ) ".
				"LEFT JOIN {field_revision_body b} ON ( nr.nid = b.entity_id AND nr.vid = b.revision_id ) ".
				"LEFT JOIN {field_revision_field_event_path_link plv} ON ( nr.nid = plv.entity_id AND nr.vid = plv.revision_id ) ".
				"LEFT JOIN {field_revision_field_sub_title st} ON ( nr.nid = st.entity_id AND nr.vid = st.revision_id ) ".
				"LEFT JOIN {field_revision_field_color_selector cs} ON ( nr.nid = cs.entity_id AND nr.vid = cs.revision_id ) ".
				"LEFT JOIN {field_revision_field_display_order dso} ON ( nr.nid = dso.entity_id AND nr.vid = dso.revision_id ) ".
				"WHERE n.status =1 ".
				"AND n.type = 'slideshow' ".
				"ORDER BY dso.field_display_order_value ASC,n.changed DESC";
	
		$result = db_query( $sql );
	
		$result_array = array();
			
		foreach ($result as $record) 
		{
			$path = $record->field_event_path_link_value;
			$title = $record->title;
			$title = preg_replace("/&#?[a-z0-9]+;/i","",$title); // removes $nbsp
			$subtitle = $record->field_sub_title_value;
			$subtitle = preg_replace("/&#?[a-z0-9]+;/i","",$subtitle); // removes $nbsp
			$body = preg_replace('#<script(.*?)>(.*?)</script>#is', '', $record->body_value);
			$body = preg_replace('#<object(.*?)>(.*?)</object>#is', '', $body);
			$teaser = preg_replace('#<img(.*?)>#is', '', $body);
			$teaser = preg_replace("/&#?[a-z0-9]+;/i","",$teaser); // removeds $nbsp
			$teaser = stripslashes($teaser);
			$teaser = strip_tags($teaser);
			
			$result_array[] = array(  'path' => $path , 
									  'title' => $title , 
									  'subtitle' => $subtitle ,
									  'teaser' => $teaser,		
									  'field_color_selector_value' => $record->field_color_selector_value , 
									  'field_image_link_value' => $record->field_event_image_cdn_link_value );	
		}
		echo json_encode( $result_array );	
	}
	
	// D7 - Block Hook
	
	// Step 1: Block Info
	function kabbalah_custom_slideshow_block_info() {
    
		$blocks['custom_slideshow'] = array(		
			'info' => t('Kabbalah Custom Slideshow'),
		);
		return $blocks;
	}
	
	// Step 2: Block View Implementation
	function kabbalah_custom_slideshow_block_view($delta = '') {
	
		// The $delta parameter tells us which block is being requested.
		switch ($delta) 
		{
			case 'custom_slideshow':
				// Create your block content here
				$block['subject'] = t('Kabbalah Custom Slideshow for front page');
				$block['content'] = kabbalah_custom_slideshow_show();
				break;
		}

		return $block;
	}
		
	function kabbalah_custom_slideshow_show() {

		drupal_add_css(drupal_get_path('module', 'kabbalah_custom_slideshow') .'/css/kabbalah_custom_slideshow.css');	
		drupal_add_js(drupal_get_path('module', 'kabbalah_custom_slideshow') .'/js/json_head_slideshow.js');	// adding the js file for the module	
		
	}
	
	// // D7 - End of Block Hook Implementation