<?php
	// Block implementation 
	// Step 1: Block Info
	function kabbalah_lesson_by_language_block_info() {
    
		$blocks['lessons_grid_view'] = array(		
			'info' => t('Lessons for a language'),
		);

		return $blocks;
	}
	
	// Step 2: Block View Implementation
	function kabbalah_lesson_by_language_block_view($delta = '') {
	
		// The $delta parameter tells us which block is being requested.
		switch ($delta) 
		{
			case 'lessons_grid_view':
				// Create your block content here
				$block['subject'] = t('Lessons By Language');
				$block['content'] = kabbalah_lessons_grid_view_show();
				break;
				
		}

		return $block;
	}
	
	function kabbalah_lessons_grid_view_show() {
		
		//Get the URL string
		$pageURL = 'http';
		//change to https
		if ($_SERVER["HTTPS"] == "on") {$pageURL .= "s";}
		$pageURL .= "://";
		  
		if ($_SERVER["SERVER_PORT"] != "80") {
			$pageURL .= $_SERVER["SERVER_NAME"].":".$_SERVER["SERVER_PORT"].$_SERVER["REQUEST_URI"];	
		}else{
			$pageURL .= $_SERVER["SERVER_NAME"].$_SERVER["REQUEST_URI"];
		}
	
		$temp = explode("/", $pageURL);	
		$collection_language = $temp[4];
		
		
		$sql =  "SELECT n.nid,n.type,n.title,n.created ".
				"FROM {node n} ".
				"LEFT JOIN {node_revision nr} ON ( n.nid = nr.nid and n.vid = nr.vid) ".
				"LEFT JOIN {field_data_field_lesson_video l} ON ( nr.nid = l.entity_id AND nr.vid = l.revision_id ) ".
				"WHERE n.status =1 ".
				"AND n.type in ('lesson') ". 
				"AND l.field_lesson_video_available_languages LIKE '%".$collection_language."%' ".
				"ORDER BY n.created DESC";
		
		$result = "";
		$result = db_query( $sql );
		$resultHTML  = "<div class='title'>Lessons with ".$collection_language." Subtitles</div>";
		$resultHTML .= "<ul class='masonry'>";
		
		foreach( $result as $record ) 
		{	
			$node = node_load($nid = $record->nid  );
			$author = taxonomy_term_load($node->field_author['und'][0]['tid']);
			$path = url(drupal_get_path_alias('node/' . $record->nid), array('absolute' => TRUE));
			$title = $node->title;
			$title = preg_replace("/&#?[a-z0-9]+;/i","",$title); // removes $nbsp
			$membership = taxonomy_term_load($node->field_lesson_group['und'][0]['tid']);
			$teaser="";
			if( sizeof($node->body) > 0 ) $teaser  = getCleanBody( $node->body['und'][0]['value'] , 100 );
			$media_type = taxonomy_term_load($node->field_type_of_lesson['und'][0]['tid']);
			
			$recorded_date = strtotime($node->field_recorded_date['und'][0]['value']);
			if( $recorded_date == "" ) $recorded_date = $node->created;
			
			if( $media_type->name == 'Video' ) 
			{
				$image_link = "http://twistassets.kabbalah.com/videos/".$node->field_lesson_video['und'][0]['twistage_existing_videos']."/screenshots/620w.jpg";
				$media_type = 'vidImg';
			} 
			else
			{
				$course_nid= node_load( $nid = $node->field_course_list['und'][0]['nid'] );
				if(!$course_nid) $course_nid = node_load( $nid = $node->field_event_list['und'][0]['nid'] );
				$image_link = $course_nid->field_image_cdn_link['und'][0]['value'];	
				$media_type = 'audioImg';
				
			}
			
			$image_link = image_style_url('course_node_image', imagecache_external_generate_path($image_link) ) ;
			
			$resultHTML .= "<li class='masonry-brick'>";
			$resultHTML .= "<span class='lessonBlockWrapper'>";	
			$resultHTML .= "<a href =".$path.">";	
			$resultHTML .= "<span class='lessonBlockImage'>";	
			$resultHTML .= "<span class='lessonBlockImageHover'></span>";	
			$resultHTML .= "<img src = '".$image_link."' class = 'imageCover' alt='".$title."' />";	
			$resultHTML .= "</span>";
			if( $subtitle != "" )
							{	
			$resultHTML .= "<span class='lessonBlockTitle'>".$subtitle."</span>";
			} else {
			$resultHTML .= "<span class='lessonBlockTitle'>".$title."</span>";
			}	
			$resultHTML .= "<span class='lessonBlockTeacherInfo'>";	
			$resultHTML .= "<span>".$author->name."</span>";	
			$resultHTML .= "</span>";	
			$resultHTML .= "<span class='lessonBlockDetail'>";	
			$resultHTML .= "<span class= '".$membership->name."'></span>";
			$resultHTML .= "<span class= '".$media_type."'></span>";		
			$resultHTML .= "<span class='lessonBlockInfo'>";
			$resultHTML .= date( 'F jS, Y',$recorded_date );
			$resultHTML .= "</span>";	
			$resultHTML .= "</span>";	
			$resultHTML .= "</a>";	
			$resultHTML .= "</span>";
			$resultHTML .= "</li>";		
			

		}	
		$resultHTML .= "</ul>";
		return 	$resultHTML;

	
		// $node = menu_get_object();
		// if ($node && $node->nid && $node->type == 'parent_course') 
		// {
			// $parent_nid = $node->nid;
			
			// if( $tid == 0 )
			// {	
				// $sql =  "SELECT n.nid,n.type,n.title,st.field_subtitle_value,il.field_image_cdn_link_value,n.nid,b.body_value,n.changed ".
						// "FROM {node n} ".
						// "LEFT JOIN {node_revision nr} ON ( n.nid = nr.nid and n.vid = nr.vid) ".
						// "LEFT JOIN {field_data_field_image_cdn_link il} ON ( nr.nid = il.entity_id AND nr.vid = il.revision_id ) ".
						// "LEFT JOIN {field_revision_body b} ON ( nr.nid = b.entity_id AND nr.vid = b.revision_id ) ".
						// "LEFT JOIN {field_data_field_subtitle st} ON ( nr.nid = st.entity_id AND nr.vid = st.revision_id ) ".
						// "LEFT JOIN {field_revision_field_parent_course pc} ON ( nr.nid = pc.entity_id AND nr.vid = pc.revision_id ) ".
						// "WHERE n.status =1 ".
						// "AND n.type in ('course') ". 
						// "AND pc.field_parent_course_nid =".$parent_nid." ".
						// "ORDER BY n.changed DESC";
			// }
			// else
			// {
				// $sql =  "SELECT n.nid,n.type,n.title,st.field_subtitle_value,il.field_image_cdn_link_value,n.nid,b.body_value,n.changed ".
						// "FROM {node n} ".
						// "LEFT JOIN {node_revision nr} ON ( n.nid = nr.nid and n.vid = nr.vid) ".
						// "LEFT JOIN {field_data_field_image_cdn_link il} ON ( nr.nid = il.entity_id AND nr.vid = il.revision_id ) ".
						// "LEFT JOIN {field_revision_body b} ON ( nr.nid = b.entity_id AND nr.vid = b.revision_id ) ".
						// "LEFT JOIN {field_data_field_subtitle st} ON ( nr.nid = st.entity_id AND nr.vid = st.revision_id ) ".
						// "LEFT JOIN {field_revision_field_parent_course pc} ON ( nr.nid = pc.entity_id AND nr.vid = pc.revision_id ) ".
						// "LEFT JOIN {taxonomy_index ti} ON( nr.nid = ti.nid ) ".
						// "LEFT JOIN {taxonomy_term_data td} ON( ti.tid = td.tid) ".
						// "WHERE n.status =1 ".
						// "AND td.vid = 7 ".
						// "AND td.tid = ".$tid." ".
						// "AND n.type in ('course') ". 
						// "AND pc.field_parent_course_nid =".$parent_nid." ".
						// "ORDER BY n.changed DESC";
					
			// }		
		
			// print $sql;
		
			// $result = "";
			// $result = db_query( $sql );
			// $resultHTML  = "";
			// $resultHTML .= "<ul class='masonry'>";
		
			// foreach( $result as $record ) {
			
				// $title = $record->title;
				// $title = preg_replace("/&#?[a-z0-9]+;/i","",$title); // removes $nbsp
				
				// $subtitle = $record->field_subtitle_value;
				// $subtitle = preg_replace("/&#?[a-z0-9]+;/i","",$subtitle); // removes $nbsp
				
				
				// $body = preg_replace('#<script(.*?)>(.*?)</script>#is', '', $record->body_value);
				// $body = preg_replace('#<object(.*?)>(.*?)</object>#is', '', $body);
				// $teaser = preg_replace('#<img(.*?)>#is', '', $body);
				// $teaser = preg_replace("/&#?[a-z0-9]+;/i","",$teaser); // removeds $nbsp
				// $teaser = stripslashes($teaser);
				// $teaser = strip_tags($teaser);
				// $pos=strpos($teaser, ' ', 100);
				// $teaser = substr( $teaser , 0 ,$pos);
				// $path = url(drupal_get_path_alias('node/' . $record->nid), array('absolute' => TRUE));	
				// $node = node_load($record->nid , NULL, TRUE);
				
				
				// if( $tid == 0 )
				// {
					// $vocab_terms3 = _taxonomy_node_get_terms_by_vocabulary($node, 7 );
					// foreach( $vocab_terms3 as $t )	{	$author_name = $t->name; }					  
				// }
				// else
				// {
					// $author_name = $url_author_name;
				// }
				
				
				// $membership = taxonomy_term_load($node->field_lesson_group['und'][0]['tid']);
				
				
				// $resultHTML .= "<li class='masonry-brick'>";
				// $resultHTML .= "<span class='lessonBlockWrapper'>";	
				// $resultHTML .= "<a href =".$path.">";	
				// $resultHTML .= "<span class='lessonBlockImage'>";	
				// $resultHTML .= "<span class='lessonBlockImageHover'></span>";	
				// $resultHTML .= "<img src = '".$record->field_image_cdn_link_value."' class = 'imageCover' alt='".$title."' />";	
				// $resultHTML .= "</span>";
				// if( $subtitle != "" )
								// {	
				// $resultHTML .= "<span class='lessonBlockTitle'>".$subtitle."</span>";
				// } else {
				// $resultHTML .= "<span class='lessonBlockTitle'>".$title."</span>";
				// }	
				// $resultHTML .= "<span class='lessonBlockTeacherInfo'>";	
				// $resultHTML .= "<span>".$author_name."</span>";	
				// $resultHTML .= "</span>";	
				// $resultHTML .= "<span class='lessonBlockDetail'>";	
				// $resultHTML .= "<span class= '".$membership->name."'></span>";
				// if( sizeof($node->field_this_course_contains) > 0 )
								// {
									// if( $node->field_this_course_contains['und'][0]['value'] == 1 ) $media_type = 'audioImg';
									// else if( $node->field_this_course_contains['und'][0]['value'] == 0 ) $media_type = 'vidImg';
									// else $media_type = 'bothAdVdImg';
								// } else {

									// $media_type = 'bothAdVdImg';
								// }	
				// $resultHTML .= "<span class= '".$media_type."'></span>";	
					
				// $resultHTML .= "<span class='lessonBlockInfo'>";
				// $resultHTML .= date( 'F jS, Y',$record->changed );
				// $resultHTML .= "</span>";	
				// $resultHTML .= "</span>";	
				// $resultHTML .= "</a>";	
				// $resultHTML .= "</span>";
				// $resultHTML .= "</li>";																			  
			
			// }
			// $resultHTML .= "</ul>";
			// return 	$resultHTML;
		// }	
	}
	