<?php
	
	/* Function returns content body based on the User Role and the Node Membership Type
     * Input : $node_id
	 * Output: Boolean true or false	
     */

	// [roles] => Array( [2] => authenticated user , [3] => administrator )	
	
	function get_membership_based_content_body( $node_id ) 
	{
		
		global $user;
		$node_data = node_load($node_id);
		$user_role = "";
		$article_membership ="";
		
		// Getting the logged in user role 
		if (array_key_exists('8', $user->roles) ) {	$user_role = $user->roles['8'];	}
		else 
		if (array_key_exists('6', $user->roles) ) {	$user_role = $user->roles['6'];	}
		else 
		if (array_key_exists('5', $user->roles) ) {	$user_role = $user->roles['5']; }
		else
		if (array_key_exists('9', $user->roles) ) {	$user_role = $user->roles['9']; }
		else
		if (array_key_exists('4', $user->roles) ) {	$user_role = $user->roles['4']; }
			
		$vocab_terms = _taxonomy_node_get_terms_by_vocabulary($node_data, 12 );
		foreach( $vocab_terms as $t )	{	$article_membership = $t->name; }
		
		//Comparing the user role and node membership 
		if( $user_role == "basic" && $article_membership == "basic") {	return true;}
		else 
		if( $user_role == "premium" && ($article_membership == "basic" || $article_membership == "premium") )  {	return true;}
		else 
		if( $user_role == "premium plus" && ($article_membership == "basic" || $article_membership == "premium" || $article_membership == "premium plus") ) {	return true;}
		else 
		if( $user->uid == 1  || ($user_role == "editor") || ($article_membership == "free")) {	return true;} // For Admin user return true
		
		return false;
		//return " article_membership : ".$article_membership." :: user_role : ".$user_role;	
	
	}

?>