<?php
	
	function ukabbalah_fp_carousals_block_info() {
  // This example comes from node.module.
  $blocks['carousal1'] = array(
    'info' => t('Beginner\'s Courses'), 
    'cache' => DRUPAL_NO_CACHE,
  );

  $blocks['carousal2'] = array(
    'info' => t('Recently Added'),
    // DRUPAL_CACHE_PER_ROLE will be assumed.
  );
  
    $blocks['carousal3'] = array(
    'info' => t('Recommended'),
    // DRUPAL_CACHE_PER_ROLE will be assumed.
  );
  
	$blocks['carousal4'] = array(
    'info' => t('Free Lessons'),
    // DRUPAL_CACHE_PER_ROLE will be assumed.
  );

  return $blocks;
}

	function ukabbalah_fp_carousals_block_view($delta = '') {
  // This example is adapted from node.module.
  $block = array();

  switch ($delta) {
    case 'carousal1':
          $block['subject'] = t('Beginner\'s Courses');
          $block['content'] = kabbalah_carousal1_show();
      break;

    case 'carousal2':
         $block['subject'] = t('Recently Added');
          $block['content'] = kabbalah_carousal2_show();
       
      break;
	  
	 case 'carousal3':
    	 $block['subject'] = t('Recommended');
          $block['content'] = kabbalah_carousal3_show();
      break;
	  
	  case 'carousal4':
    	 $block['subject'] = t('Free Lessons');
          $block['content'] = kabbalah_carousal4_show();
      break;
  }
  return $block;
}
			
	function kabbalah_carousal1_show() {
	
		$jsonurl = '/k_api/bgnr_crs';
		drupal_add_js(drupal_get_path('module', 'ukabbalah_fp_carousals') .'/js/fp_carousal.js');	// adding the js file for the module	
		drupal_add_js(array('fp_vars1' => array('divid' => 'beginnerCourse','jsonurl'=>$jsonurl)), 'setting');
		return "<div class='allCoursesWrapper'><span class='allCourses'><a href='/beginners-courses'>view all</a></span><span class='startHere'>If you are new to the teachings of The Kabbalah Centre, start here</span></div><div id='beginnerCourse'></div>";
	
	}
	
	function kabbalah_carousal2_show() {
	
		$jsonurl1 = '/k_api/recently_added_lsns';
		$jsonurl2 = '/k_api/recently_added_crs';
		
		drupal_add_js(drupal_get_path('module', 'ukabbalah_fp_carousals') .'/js/fp_carousal.js');	// adding the js file for the module	
		drupal_add_js(array('fp_vars2' => array('divid' => 'recentlyAddedLessons','jsonurl'=>$jsonurl1)), 'setting');
		drupal_add_js(array('fp_vars4' => array('divid' => 'recentlyAddedCourses','jsonurl'=>$jsonurl2)), 'setting');
		
		return "<div id='recentTabWrapper'><span id='recentLessonTab' class='recentTab activeTap'>LESSONS</span><span id='recentCourseTab' class='recentTab'>COURSES</span><span class='allRecentlyAdded'><a href='/courses'>view all</a></span></div><div id='recentlyAddedLessons'></div><div id='recentlyAddedCourses'></div>";
	
	}
	
	function kabbalah_carousal3_show() {
	
		$jsonurl = '/k_api/recommended_lsns/1/0;
		drupal_add_js(drupal_get_path('module', 'ukabbalah_fp_carousals') .'/js/fp_carousal.js');	// adding the js file for the module	
		drupal_add_js(array('fp_vars3' => array('divid' => 'recommendedCourses','jsonurl'=>$jsonurl)), 'setting');
		
		$today_date_month = date('n',time());
		$today_date_year = date('Y',time());
		
		$ch = curl_init();
		curl_setopt($ch, CURLOPT_URL,"http://www.hebcal.com/converter/?cfg=json&gy=".$today_date_year."&gm=".$today_date_month."&g2h=1");
		// receive server response ...
		curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
		$server_output = curl_exec ($ch);
		curl_close ($ch);
		$heb_date_info = json_decode($server_output);
		
		$heb_date = $heb_date_info->hm.' '.$heb_date_info->hy;
		
		return "<div id='recommendedDateWrapper'><span class='recommendedDate'>This week: ".date('M j',strtotime('monday this week'))." - ".date('M j',strtotime('sunday this week')).", ".date('Y',time())." | </span><span class='recommendedHebDate'>".$heb_date."</span></div><div id='recommendedCourses'></div>";
	
	}
	
	function kabbalah_carousal4_show() {
	
		$jsonurl = '/k_api/free_lsns';
		drupal_add_js(drupal_get_path('module', 'ukabbalah_fp_carousals') .'/js/fp_carousal.js');	// adding the js file for the module	
		drupal_add_js(array('fp_vars5' => array('divid' => 'freeLessons','jsonurl'=>$jsonurl)), 'setting');
		return "<div class='allCoursesWrapper'><span class='allCourses'><a href='/free-lessons'>view all</a></span></div><div id='freeLessons'></div>";
	
	}