<?php
	
	// Implementation Menu Hook 	 
	function kabbalah_teachers_bio_menu() {
		
		$items = array();
		
		$items['getTeacherBioByName/%'] = array(               // Made this a PAGE
			'page callback'      => 'getTeacherBioByName',
			'page arguments' => array(1),
			'access callback' => TRUE,
			'type'             => MENU_CALLBACK,
		);
				
		return $items;
	}
	
	
	
	function getTeacherBioByName( $name ) {
	
		$name = urlencode($name);
		$url = "http://kabbalah.com/getTeacherBioByName/".$name;
		//echo $url;
		$ch = curl_init();
		curl_setopt($ch, CURLOPT_URL,$url);
		// receive server response ...
		curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
		$server_output = curl_exec ($ch);
		curl_close ($ch);
		$teachers_info = array();
		$teachers_info = json_decode( $server_output );
		
		echo json_encode($teachers_info);
	
	
	}
